export type TypeofValues =
  | 'string'
  | 'number'
  | 'boolean'
  | 'undefined'
  | 'object'
  | 'function'
  | 'symbol'
  | 'bigint';

export type ObjectTypeValues =
  | 'Null'
  | 'Undefined'
  | 'Boolean'
  | 'Number'
  | 'String'
  | 'Symbol'
  | 'BigInt'
  | 'Function'
  | 'Array'
  | 'Date'
  | 'RegExp'
  | 'Object'
  | 'Error'
  | 'Map'
  | 'Set'
  | 'WeakMap'
  | 'WeakSet'
  | 'Arguments'
  | 'JSON'
  | 'TypedArray'
  | 'ArrayBuffer'
  | 'DataView'
  | 'Promise'
  | 'Generator'
  | 'GeneratorFunction'
  | 'AsyncFunction'
  | 'Reflect';
